### ISSUE TITLE
How does this compare to the other rollup-plugin-swc

### ISSUE THREAD

**Issue by shaulgo** [SukkaW/rollup-plugin-swc#10]
Hey, I see there is another plugin for swc. Do you know how they compare? https://github.com/mentaljam/rollup-plugin-swc

**Comment by SukkaW** [comment]
So here is why I made my own rollup swc plugin:

- It can reads configuration from `tsconfig.json` and `jsconfig.json` file automatically
- Unlike https://github.com/mentaljam/rollup-plugin-swc (which run swc minify on every `transform`), my plugin only run swc minify on `renderChunk`, which will can minify all chunks at once.
- It works well with other rollup plugins (like rollup commonjs plugin)
  - Earlier versions of swc can not handle rollup virtual module specifier `\0` correctly, my plugin has a workaround for it (https://github.com/swc-project/swc/issues/2853, https://github.com/SukkaW/rollup-plugin-swc/pull/2)
- Better testing.

**Comment by SukkaW** [comment]
A comparison has been added in 29c7dface24ac4781af6340ebca80aabfd5317fa.
