### ISSUE TITLE
Sourcemaps seem to be broken when using minifcation

### ISSUE THREAD

**Issue by ghost91-** [SukkaW/rollup-plugin-swc#11]
When using minification, sourcemap creation seems to be broken, it just creates a source map with content like this:
```json
{"version":3,"file":"ds4.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```
I set `sourcemap` to `true` in the `output` part of the rollup config, and use the following swc plugin configuration
```js
        swc({ minify: true, sourceMaps: true }),
```
It works perfectly fine when `minify` is set to `false`.

**Comment by SukkaW** [comment]
`rollup-plugin-swc` is using swc's `minify` named export (which only accepts `jsc.minify` as its second argument) to do minification during the `renderChunks` phase:

https://github.com/SukkaW/rollup-plugin-swc/blob/001f15aead43c235b5954ce35e3567bc8757b4ec/src/index.ts#L148-L151

And swc has a undocumented, dedicated `sourceMap` option for `jsc.minify`:

https://github.com/swc-project/swc/blob/ee959ee2f680965df3842c4010073e35bceeb92a/node-swc/src/types.ts#L34

Try with the option see if it works:

```js
swc({
  minify: true,
  jsc: { minify: { sourceMap: true } },
  sourceMaps: true
})
```

**Comment by ghost91-** [comment]
Thanks, it works perfectly this way!

May I suggest adding this to the README? I think it could help a lot of people who might run into the same problem.

Closing the issue as there is no bug and the problem has been solved.

**Comment by SukkaW** [comment]
> Thanks, it works perfectly this way!
> 
> May I suggest adding this to the README? I think it could help a lot of people who might run into the same problem.
> 
> Closing the issue as there is no bug and the problem has been solved.

The issue is due to the unclearness of SWC's documentation.

Actually, I am about to create an Issue at SWC, complaining about the minify behavior and the documentation, and it should be fixed by swc at its end.
