### ISSUE TITLE
Is this plugin duplicated? 

### ISSUE THREAD

**Issue by omerman** [SukkaW/rollup-plugin-swc#18]
I see there is the exact same plugin. 
[This one](https://github.com/mentaljam/rollup-plugin-swc).. Is there any difference?

**Comment by SukkaW** [comment]
@omerman I have included a full comparison in the README: https://github.com/SukkaW/rollup-plugin-swc#comparison

**Comment by omerman** [comment]
Oops, must of missed it 😳
