### ISSUE TITLE
Unable to use ES module configuration file since `0.9.1`

### ISSUE THREAD

**Issue by Systemcluster** [SukkaW/rollup-plugin-swc#39]
Since `0.9.1`, `rollup-plugin-swc` fails to execute when using an ES module configuration file. 

```
release-branch:build: > tsc && rollup -c
release-branch:build:
release-branch:build: (node:26136) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
release-branch:build: (Use `node --trace-warnings ...` to show where the warning was created)
release-branch:build: [!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.
release-branch:build:
release-branch:build: Original error: Cannot use import statement outside a module
release-branch:build: https://rollupjs.org/command-line-interface/#bundleconfigascjs
release-branch:build: D:\Development\actions\node_modules\.pnpm\rollup-swc-preserve-directives@0.3.0_@swc+core@1.3.69_rollup@3.26.3\node_modules\rollup-swc-preserve-directives\dist\es\index.js:1
release-branch:build: import { extname } from 'path';
release-branch:build: ^^^^^^
release-branch:build:
release-branch:build: SyntaxError: Cannot use import statement outside a module
release-branch:build:     at internalCompileFunction (node:internal/vm:73:18)
release-branch:build:     at wrapSafe (node:internal/modules/cjs/loader:1153:20)
release-branch:build:     at Module._compile (node:internal/modules/cjs/loader:1197:27)
release-branch:build:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
release-branch:build:     at Module.load (node:internal/modules/cjs/loader:1091:32)
release-branch:build:     at Function.Module._load (node:internal/modules/cjs/loader:938:12)
release-branch:build:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
release-branch:build:     at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
release-branch:build:     at DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
release-branch:build:     at importModuleDynamicallyWrapper (node:internal/vm/module:428:15)
release-branch:build:
release-branch:build:
release-branch:build:  ELIFECYCLE  Command failed with exit code 1.
release-branch:build: ERROR: command finished with error: command (D:\Development\actions\actions\release-branch) pnpm run build exited (1)
```

This seems to be an issue with https://github.com/huozhi/rollup-plugin-swc-preserve-directives, but directly affects users of this package in a patch version update.

Reproducible with https://github.com/Systemcluster/actions, replace `"=0.9.0"` in `configs/rollup-config-workspace/package.json` with `^0.9.1` and run `npm build`.

**Comment by SukkaW** [comment]
Thanks for your report! I will make a PR to [`rollup-plugin-swc-preserve-directives`](https://github.com/huozhi/rollup-plugin-swc-preserve-directives) to fix this!

**Comment by SukkaW** [comment]
@Systemcluster FYI, I have created a PR at [rollup-plugin-swc-preserve-directives](https://github.com/huozhi/rollup-plugin-swc-preserve-directives).

In the meantime, would you like to try patching your `node_modules` with the following steps to see if my PR actually works:

- Rename `node_modules/rollup-swc-preserve-directives/dist/es/index.js` to `node_modules/rollup-swc-preserve-directives/dist/es/index.mjs`
- Find all `dist/es/index.js` inside the `node_modules/rollup-swc-preserve-directives/package.json` and replace them all with `dist/es/index.mjs`
- Re-run `rollup -c` with `rollup-plugin-swc3@0.9.1`

**Comment by Systemcluster** [comment]
Works 👍

**Comment by SukkaW** [comment]
> Works 👍

Thanks for your feedback! So https://github.com/huozhi/rollup-plugin-swc-preserve-directives/pull/7 should probably fix your issue!

**Comment by Systemcluster** [comment]
Resolved with the release of https://github.com/huozhi/rollup-plugin-swc-preserve-directives/releases/tag/v0.3.1, thanks for the quick response!
