### ISSUE TITLE
SWC packaging doubles the size of the file

### ISSUE THREAD

**Issue by libondev** [SukkaW/rollup-plugin-swc#4]
My package size was 5.43kb before using rollup-plugin-swc3 and using swc replacement `rollup-plugin-typescript2` / `@rollup / plugin-babel` / `rollup-plugin-terser` plugin grew to 10.79kb is there a question of variable repeat references?

![](https://img.fy6b.com/2021/11/29/ee64603f9461d.png)
![](https://img.fy6b.com/2021/11/29/042ad96788c48.png)

**Comment by SukkaW** [comment]
@banlify Any demo or minimum reproduction?

**Comment by libondev** [comment]
> @banlify Any demo or minimum reproduction?

https://github.com/banlify/swc-build-test

`npm run build` and `npm run build:swc`.

You can also view the packaged files under `dist/`

**Comment by SukkaW** [comment]
> > @banlify Any demo or minimum reproduction?
> 
> https://github.com/banlify/swc-build-test
> 
> `npm run build` and `npm run build:swc`.
> 
> You can also view the packaged files under `dist/`

`@monitor/utils` seems to be an external dependency, which will not be processed by the plugin by default.

Use option `exclude: null` (or `exclude: /node_modules/core-js`) to let swc process your external dependency.

**Comment by libondev** [comment]
> > > @banlify Any demo or minimum reproduction?
> > 
> > 
> > https://github.com/banlify/swc-build-test
> > `npm run build` and `npm run build:swc`.
> > You can also view the packaged files under `dist/`
> 
> `@monitor/utils` seems to be an external dependency, which will not be processed by the plugin by default.
> 
> Use option `exclude: null` (or `exclude: /node_modules/core-js`) to let swc process your external dependency.

No, it is not an external dependency, it is a file in my Packages /utils folder, I am using PNPM's Monorepo mode
