### ISSUE TITLE
Remove experimental decorators check from SWC config

### ISSUE THREAD

**Issue by scssyworks** [SukkaW/rollup-plugin-swc#40]
In current code we are enabling `decorators` using `experimentalDecorators` check from tsconfig. This is no longer needed since TypeScript 5 supports decorators stage 3 proposal without a flag. Additionally `experimentalDecorators` flag enables the legacy decorators and SWC now supports decorators stage 3 proposal as of version 1.3.47 (See: https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion).

I will be raising a pull request for proposed changes. Let me know your thoughts.

**Comment by SukkaW** [comment]
That makes sense. Looking forward to your PR!

**Comment by SukkaW** [comment]
@scssyworks Hello, are you still planning to create the PR for your proposal?

Also, should we detect whether a user is using TypeScript 5, to avoid the breaking change?

**Comment by SukkaW** [comment]
The is fixed by #65 and a new release including this will be released soon!
