### ISSUE TITLE
Error: `env` and `jsc.target` cannot be used together

### ISSUE THREAD

**Issue by marioparaschiv** [SukkaW/rollup-plugin-swc#42]
I am compiling for a very specific React Native environment which doesn't have all features from ECMAScript 2022 but has some of the most important ones. 

This is my config.
![image](https://github.com/SukkaW/rollup-plugin-swc/assets/98427312/f0fc3d55-769b-4aa9-a7a3-5a970965df52)

This is my TSConfig.
![image](https://github.com/SukkaW/rollup-plugin-swc/assets/98427312/51116546-4468-482e-8875-0c42f3e3e667)

The issue is from this plugin reading the tsconfig and applying `jsc.target` automatically, which is impossible to prevent as it is overridden if specified in the plugin parameters or the `.swcrc` file.

**Comment by SukkaW** [comment]
Since you are already using `.swcrc`, IMHO you can disable the automatically reading tsconfig feature (by passing `{ tsconfig: false }` to the plugin option).

**Comment by marioparaschiv** [comment]
The `tsconfig` option does not work for me when setting it to false. 
![image](https://github.com/SukkaW/rollup-plugin-swc/assets/98427312/59c9dd85-65e7-48e7-bf29-f9debe724668)

**Comment by SukkaW** [comment]
> The `tsconfig` option does not work for me when setting it to false.

That's strange. I will look into this.

**Comment by SukkaW** [comment]
Sorry, but I am not able to reproduce your issue. To prove that `rollup-plugin-swc3` and `{ tsconfig: false }` are working as intended, I have created a unit test case, see #43 and https://github.com/SukkaW/rollup-plugin-swc/commit/1b8e6ca0f55464a213eaa5e44afc28fb08211e93.

If you can provide a minimum reproduction of your problem, feel free to ping me or open a new issue, and I will dig into it.

**Comment by marioparaschiv** [comment]
I figured out the issue. My rollup config file was .ts which meant I had to run it with `rollup -c —configPlugin rollup-plugin-swc3` which caused the error as it was reading tsconfig.
