### ISSUE TITLE
Cannot handle export ts type

### ISSUE THREAD

**Issue by huozhi** [SukkaW/rollup-plugin-swc#47]
### Expect behavior

I can export ts type in ts entry file, and in output it could be erased in js asset. And rollup won't complain about resolving

### Observed behavior

```
src/index.ts → stdout...
(!) Missing exports
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
src/index.ts
IConfig is not exported by src/types.ts
1: import { IConfig } from './types';
            ^
2:
3: export { IConfig }
[!] RollupError: "IConfig" is not exported by "src/types.ts", imported by "src/index.ts".
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
src/index.ts (1:9)
1: import { IConfig } from './types';
            ^
2:
3: export { IConfig }

```

###  Reproduction

https://github.com/beeebox/swc3-export-type-repro

**Comment by SukkaW** [comment]
Thanks for the report, I will look into this!

**Comment by SukkaW** [comment]
@huozhi 

I've found the cause of the issue. But as it stands, it seems unfixable:

- SWC operates as a single file transformer without the cross-file functionality. When transforming `src/index.ts`, SWC doesn't know the existence of `src/types.ts`.
- Rollup, serving as a bundler, acknowledges every file's existence but doesn't work with the type information.
- Consequently, neither SWC nor Rollup can determine whether `IConfig` in `import { IConfig } from './types'` is a type or a value.

You can workaround the issue by explicitly declaring `IConfig` as a type-only import: 

```ts
import type { IConfig } from './types';
// or
import { type IConfig } from './types';
```

This can be enforced / auto-fixed through the use of the `@typescript-eslint/eslint-plugin` with the [`@typescript-eslint/consistent-type-imports`](https://typescript-eslint.io/rules/consistent-type-imports/) rule:

```js
"@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }]
```
