### ISSUE TITLE
Verify rollup v4 works and add to peerDependencies

### ISSUE THREAD

**Issue by JustinGrote** [SukkaW/rollup-plugin-swc#48]
Hello,

rollup v4 was published today, so needs a compatibility check and added to peerDependencies. Works just fine so far in my limited scenario.

Plugin API changes to check are here: https://github.com/rollup/rollup/releases/tag/v4.0.0

**Comment by SukkaW** [comment]
@JustinGrote Sure!

I will test Rollup 4 against the existing test suite first and check if everything still works!

----

Update: all test cases do pass, and I've released a new version `0.10.2` to include the change!

**Comment by JustinGrote** [comment]
@SukkaW thanks!
