### ISSUE TITLE
Compact Output?

### ISSUE THREAD

**Issue by leonardssh** [SukkaW/rollup-plugin-swc#5]
Can't you do something like: https://swc.rs/docs/usage/bundling#compact-output for rollup?

I mean to fix the ts paths as well, because at the moment they import them as they are.

### With `rollup-plugin-swc`
```js
'use strict';

var _constants = require("@shared/constants");
mp.events.add('playerReady', function(player) {
    console.log("".concat(player.name, " is ready!"));
    player.customProperty = 1;
    player.customMethod = function() {
        console.log('customMethod called.');
    };
    player.customMethod();
});
console.log(_constants.SHARED_CONSTANTS.HELLO_WORLD);
```

### With `rollup-plugin-typescript2`
```js
'use strict';

const SHARED_CONSTANTS = {
    HELLO_WORLD: 'HELLO WORLD!'
};

mp.events.add('playerReady', (player) => {
    console.log(`${player.name} is ready!`);
    player.customProperty = 1;
    player.customMethod = () => {
        console.log('customMethod called.');
    };
    player.customMethod();
});
console.log(SHARED_CONSTANTS.HELLO_WORLD);

```

**Comment by SukkaW** [comment]
The bundling should be processed by the rollup, and swc only does transformation here. (swcpack is still under heavy development, which is also why I develop the plugin in the first place).

I don't know why the bundling is not working in your case. Where do you put `swc` in your `rollup.config.js`?

**Comment by leonardssh** [comment]
I've something like this:

```ts
// packages/server/tsconfig.json
{
	"compilerOptions": {
		"baseUrl": "./",
		"paths": {
			"@shared/*": ["../shared/*"],
		}
	}
}

// packages/server/index.ts
import shared from '@shared';

console.log(shared.something);
```
```js
// rollup.config.js
{
		input: resolvePath([sourcePath, 'server', 'index.ts']),
		output: {
			file: resolvePath([buildOutput, 'packages', 'core', 'index.js']),
			format: 'cjs'
		},
		plugins: [
			json(),
			babel({ babelHelpers: 'bundled' }),
			commonjs(),
			resolve({ browser: true }),
			swc({
				tsconfig: '../packages/server/tsconfig.json',
				minify: true,
				jsc: {
					parser: {
						syntax: 'typescript',
						tsx: true
					},
					target: 'es2018',
                                        baseUrl: './',
					paths: {
						"@shared/*": ["../shared/*"],
					}
				},
				module: {
					type: 'es6'
				}
			}),
			productionMode
		],
		external: [...localInstalledPackages],
		inlineDynamicImports: true
	},
```

But it compiles as follows:
```js
'use strict';

var shared = require("@shared");
console.log(shared.something);
```

**Comment by leonardssh** [comment]
I tried to implement SWC in [ragemp-typescript](https://github.com/LeonardSSH/ragemp-typescript), but without success. (local only)

**Comment by SukkaW** [comment]
> I've something like this:
> 
> ```ts
> // packages/server/tsconfig.json
> {
> 	"compilerOptions": {
> 		"baseUrl": "./",
> 		"paths": {
> 			"@shared/*": ["../shared/*"],
> 		}
> 	}
> }
> 
> // packages/server/index.ts
> import shared from '@shared';
> 
> console.log(shared.something);
> ```

I see why. Since Rollup is doing the bundling (not swc), configuring it in swc will not have the effect.

You probably need [rollup-ts-paths](https://github.com/bitshiftza/rollup-plugin-ts-paths) (has `tsconfig.json` supports) or [@rollup/plugin-alias](https://www.npmjs.com/package/@rollup/plugin-alias) for this. Add the plugin before `swc`.

**Comment by leonardssh** [comment]
These 2 plugins only give me replace on the path, not resolve and include it in the output file.
I need what I've included from that path to be included in my output file.

e.g
```ts
// shared.ts
export const gobrr = "gobrrr";
```

```ts
// tsconfig
{
	"compilerOptions": {
		"baseUrl": "./",
		"paths": {
			"Shared": ["shared/shared.ts"],
		}
	}
}
```

```ts
// index.ts
import { gobrr } from 'Shared';

console.log(gobrr);
```

Output:
```js
'use strict';

const gobrr = "gobrrr";
console.log(gobrr);
```

**Comment by SukkaW** [comment]
@LeonardSSH

I do find some fundamental flaws with `rollup-ts-paths`, but I am able to get `@rollup/plugin-alias` working.

```js
// src/index.ts
import { foo } from 'Shared';
console.log(foo);

// src/shared.ts
export const foo = 'bar';

// rollup.config.js
const { swc } = require('rollup-plugin-swc3');
const { nodeResolve } = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const alias = require('@rollup/plugin-alias');

export default {
  input: './src/index.ts',
  output: { file: './dist/index.js' },
  plugins: [
    alias({
      entries: {
        Shared: './shared',
      }
    }),
    nodeResolve({ browser: true }),
    commonjs(),
    swc()
  ]
}

// dist/index.js
var foo = 'bar';

console.log(foo);
```

I don't know why it failed in your case.

Also, my example works without `nodeResolve` and `commonjs`. I add them just because you add them in your rollup config.

**Comment by SukkaW** [comment]
```js
// src/index.ts
import { foo } from 'Shared';
console.log(foo);

// src/shared.ts
export const foo = 'bar';

// rollup.config.js
const { swc } = require('rollup-plugin-swc3');

export default {
  input: './src/index.ts',
  output: { file: './dist/index.js' },
    swc({
      jsc: {
        baseUrl: './src',
        paths: {
          'Shared': ['./shared.ts']
        }
      }
    })
  ]
}

// dist/index.js
var foo = 'bar';

console.log(foo);
```

@LeonardSSH I can even get this to work. So it is not an issue with my plugin.

**Comment by leonardssh** [comment]
@SukkaW yeah, now I see it works, thx so much. ❤

**Comment by SukkaW** [comment]
@LeonardSSH Also, reading `baseUrl` & `paths` from `tsconfig.json` is added in https://github.com/SukkaW/rollup-plugin-swc/commit/290263aff050afb87888196aa6735e3b90c70055 and will be landed in the next version.
