### ISSUE TITLE
Circular dependency issue

### ISSUE THREAD

**Issue by renataogarcia** [SukkaW/rollup-plugin-swc#58]
I'm getting a circular dependency warning on [eventemitter3](https://github.com/primus/eventemitter3), which causes the bundle to fail.

I've reported the [issue here](https://github.com/primus/eventemitter3/issues/265), but later found that it only happens if I'm using `rollup-plugin-swc3` plugin, and it works fine with `@rollup/plugin-typescript` and `@rollup/plugin-swc`. Plain JS also works fine.

On `eventemitter3` the [index.mjs](https://github.com/primus/eventemitter3/blob/a650549176ded0d0dcc52e27b03ae5669d7dcd7c/index.mjs#L1C18-L1C18) ESM wrapper  imports index.js. The other plugins resolve `index.js` to `index.js` however `rollup-plugin-swc3` [resolves](https://github.com/SukkaW/rollup-plugin-swc/blob/2a3b06ac8e2dbaea5fa4d36a369df48827d32d9d/src/index.ts#L61) it to `index.mjs`. Which causes the circular dependency problem. 

I was able to workaround it and make it work by changing the order in the `extensions` configuration. However, I was wondering if this is a bug since only `rollup-plugin-swc3` behaves this way.

**Comment by SukkaW** [comment]
@renataogarcia The bugfix is included in the release `0.11.0`.
