### ISSUE TITLE
Reading `.swcrc` automatically?

### ISSUE THREAD

**Issue by Phryxia** [SukkaW/rollup-plugin-swc#62]
Thank you for great plugin. I've used this for a long time.
I wonder whether this plugin search or take care `.swcrc` or not.
I've read your source code and found nothing about it, but still  I'm not sure.

If it's not supported currently, do you have a plan for partial/full support for `.swcrc`?

**Comment by SukkaW** [comment]
`@swc/core` should have read the `.swcrc` file automatically, but I didn't add any test cases against this.

**Comment by Phryxia** [comment]
@SukkaW 

> @swc/core should have read the .swcrc file automatically, but I didn't add any test cases against this.

Ok, then I think considering `filename` would be sufficient. Is there any other option ignored by plugin except `filename`? If it doesn't, there is nothing to worry IMO so that close this issue. (Maybe it's better to mention [that behavior](https://github.com/SukkaW/rollup-plugin-swc/issues/62#issuecomment-1916837948) in README)

Thank you for replying.

**Comment by SukkaW** [comment]
Closing the issue as you can enable `.swcrc` by passing `swcrc: true` to the option. This is supported by `@swc/core` natively.
