### ISSUE TITLE
The settings "experimentalDecorators": true and "emitDecoratorMetadata": true stopped working in version 0.12.0.

### ISSUE THREAD

**Issue by cjnoname** [SukkaW/rollup-plugin-swc#66]
The settings "experimentalDecorators": true and "emitDecoratorMetadata": true stopped working in version 0.12.0.

**Comment by SukkaW** [comment]
Might related to https://github.com/SukkaW/rollup-plugin-swc/pull/65/

cc @nonzzz

**Comment by nonzzz** [comment]
Is there any log?

**Comment by nonzzz** [comment]
I guess you want use `decorator` with legacy mode?

**Comment by cjnoname** [comment]
> I guess you want use `decorator` with legacy mode?

We use typeorm

**Comment by SukkaW** [comment]
@cjnoname #67 is merged and we will release a new version soon!

**Comment by cjnoname** [comment]
> @cjnoname #67 is merged and we will release a new version soon!

Thanks mate!

**Comment by cjnoname** [comment]
> @cjnoname #67 is merged and we will release a new version soon!

It works, many thanks!

**Comment by nonzzz** [comment]
@cjnoname Close it, pls.
